// classes action type
export const  GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const  GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const  GET_CLASSES_FAILED = 'GET_CLASSES_FAILED';

// add 
export const  POST_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const  POST_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const  POST_CLASSES_FAILED = 'GET_CLASSES_FAILED';

// instructor action type
export const  GET_INSTRUCTOR_REQUEST = 'GET_INSTRUCTOR_REQUEST';
export const  GET_INSTRUCTOR_SUCCESS = 'GET_INSTRUCTOR_SUCCESS';
export const  GET_INSTRUCTOR_FAILED = 'GET_INSTRUCTOR_FAILED';

